[build]
builder = "NIXPACKS"

[deploy]
startCommand = "uvicorn src.api:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[env]
PYTHONUNBUFFERED = "1"
ANONYMIZED_TELEMETRY = "False"
CHROMA_SERVER_NOFILE = "1"
