[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Railway environment variables you should set in the dashboard:
# RAILWAY_HEALTHCHECK_TIMEOUT_SEC=300
# RAILWAY_DEPLOYMENT_TIMEOUT_SEC=1800