[build]
builder = "dockerfile"
buildCommand = "echo 'Using Dockerfile build'"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 120  # Increased for ML app startup
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "python -m uvicorn src.api:app --host 0.0.0.0 --port $PORT --workers 1"

# Resource limits and timeouts
[deploy.env]
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
PIP_NO_CACHE_DIR = "1"